// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sQd0Rt1b4dJYkvJM0SSYyGcNb-r4KOA',
    appId: '1:96848600393:web:f133ffced2898d7c23ce98',
    messagingSenderId: '96848600393',
    projectId: 'emeraum',
    authDomain: 'emeraum.firebaseapp.com',
    storageBucket: 'emeraum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8pU7-iRYH8R-ktuFgwmno86Kityw9PG4',
    appId: '1:96848600393:android:726cd94e0384a35423ce98',
    messagingSenderId: '96848600393',
    projectId: 'emeraum',
    storageBucket: 'emeraum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzFjwUyj7q2RKM6e5J8vugXg3mNE728k',
    appId: '1:96848600393:ios:5c4fb3073725bf2323ce98',
    messagingSenderId: '96848600393',
    projectId: 'emeraum',
    storageBucket: 'emeraum.firebasestorage.app',
    iosBundleId: 'com.example.emeron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOzFjwUyj7q2RKM6e5J8vugXg3mNE728k',
    appId: '1:96848600393:ios:5c4fb3073725bf2323ce98',
    messagingSenderId: '96848600393',
    projectId: 'emeraum',
    storageBucket: 'emeraum.firebasestorage.app',
    iosBundleId: 'com.example.emeron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2sQd0Rt1b4dJYkvJM0SSYyGcNb-r4KOA',
    appId: '1:96848600393:web:97c6693761278e9423ce98',
    messagingSenderId: '96848600393',
    projectId: 'emeraum',
    authDomain: 'emeraum.firebaseapp.com',
    storageBucket: 'emeraum.firebasestorage.app',
  );
}